// <auto-generated />
namespace PilotProject.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SecondSmallChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecondSmallChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201301031710395_SecondSmallChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
