// <auto-generated />
namespace PilotProject.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class newfield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newfield));
        
        string IMigrationMetadata.Id
        {
            get { return "201301032342157_new-field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
